### ISSUE TITLE
Weekly Report 2024-09-12

### ISSUE THREAD

**Issue by JingwenJessica** [Etown-CS/EtownCoursePlanner#5]
What did you do this week?

**Comment by danistrausburger** [comment]
I helped with two of our client/persona interviews. I also worked with my team to create a features and ideas list for our project. I also worked on the wiki page.

**Comment by IsabelM8** [comment]
I started writing up the persona/user stories and worked with the others to come up with a list of goals and ideas for this project.

**Comment by MelissaPatton** [comment]
I worked with my team to create a list of goals and ideas that we think the project should include and asked some students if they had anything else to add outside of class.

**Comment by Stephaniemotz** [comment]
I worked with my team by starting discussions within our GitHub that focused on our initial ideas, created our wiki page, and helped facilitate client interviews.
